tmpl: improve dedelegation recipe args and error handling

diff --git a/templates/cardano-parts-project/Justfile b/templates/cardano-parts-project/Justfile
--- a/templates/cardano-parts-project/Justfile
+++ b/templates/cardano-parts-project/Justfile
@@ -10,8 +10,16 @@ statePrefix := "~/.local/share"
 
 # Common code
 checkEnv := '''
-  ENV="${1:-}"
   TESTNET_MAGIC="${2:-""}"
+''' + checkEnvWithoutOverride + '''
+  # Allow a magic override if the just recipe optional var is provided
+  if ! [ -z "${TESTNET_MAGIC:-}" ]; then
+    MAGIC="$TESTNET_MAGIC"
+  fi
+'''
+
+checkEnvWithoutOverride := '''
+  ENV="${1:-}"
 
   if ! [[ "$ENV" =~ mainnet$|preprod$|preview$|private$|sanchonet$|shelley-qa$|demo$ ]]; then
     echo "Error: only node environments for demo, mainnet, preprod, preview, private, sanchonet and shelley-qa are supported"
@@ -32,11 +40,6 @@ checkEnv := '''
     MAGIC="5"
   elif [ "$ENV" = "demo" ]; then
     MAGIC="42"
-  fi
-
-  # Allow a magic override if the just recipe optional var is provided
-  if ! [ -z "${TESTNET_MAGIC:-}" ]; then
-    MAGIC="$TESTNET_MAGIC"
   fi
 '''
 
@@ -174,18 +177,30 @@ dbsync-create-faucet-stake-keys-table ENV HOSTNAME NUM_ACCOUNTS="500":
   echo "Executing stake key sql injection command for environment {{ENV}}..."
   just ssh {{HOSTNAME}} -t "psql -XU cexplorer cexplorer < \"$TMPFILE\""
 
-dedelegate-non-performing-pools ENV TESTNET_MAGIC=null *STAKE_KEY_INDEXES=null:
+dedelegate-non-performing-pools ENV *STAKE_KEY_INDEXES=null:
   #!/usr/bin/env bash
   set -euo pipefail
-  {{checkEnv}}
+  {{checkEnvWithoutOverride}}
+
+  if [ "{{ENV}}" = "mainnet" ]; then
+    echo "Dedelegation cannot be performed on the mainnet environment"
+    exit 1
+  fi
   just set-default-cardano-env {{ENV}} "$MAGIC" "$PPID"
 
+  if [ "$(jq -re .syncProgress <<< "$(just query-tip {{ENV}})")" != "100.00" ]; then
+    echo "Please wait until the local tip of environment {{ENV}} is 100.00 before dedelegation"
+    exit 1
+  fi
+
+  echo
+  read -p "Press any key to start de-delegating {{ENV}} faucet pool delegations for stake key indexes {{STAKE_KEY_INDEXES}}" -n 1 -r -s
   echo
   echo "Starting de-delegation of the following stake key indexes: {{STAKE_KEY_INDEXES}}"
   for i in {{STAKE_KEY_INDEXES}}; do
     echo "De-delegating index $i"
     NOMENU=true scripts/restore-delegation-accounts.py \
-      --testnet-magic {{TESTNET_MAGIC}} \
+      --testnet-magic "$MAGIC" \
       --signing-key-file <(just sops-decrypt-binary secrets/envs/{{ENV}}/utxo-keys/rich-utxo.skey) \
       --wallet-mnemonic <(just sops-decrypt-binary secrets/envs/{{ENV}}/utxo-keys/faucet.mnemonic) \
       --delegation-index "$i"
