tmpl recipe: adds cardano-testnet recipe

diff --git a/templates/cardano-parts-project/Justfile b/templates/cardano-parts-project/Justfile
--- a/templates/cardano-parts-project/Justfile
+++ b/templates/cardano-parts-project/Justfile
@@ -289,6 +289,29 @@ build-machines *ARGS:
   let nodes = (nix eval --json '.#nixosConfigurations' --apply builtins.attrNames | from json)
   for node in $nodes {just build-machine $node {{ARGS}}}
 
+# Run a local cardano-testnet
+cardano-testnet isNg *ARGS:
+  #!/usr/bin/env bash
+  set -euo pipefail
+
+  if [ "{{isNg}}" = "true" ]; then
+    CARDANO_CLI=$(command -v cardano-cli-ng)
+    CARDANO_NODE=$(command -v cardano-node-ng)
+    CARDANO_TESTNET="cardano-testnet-ng"
+  elif [ "{{isNg}}" = "false" ]; then
+    CARDANO_CLI=$(command -v cardano-cli)
+    CARDANO_NODE=$(command -v cardano-node)
+    CARDANO_TESTNET="cardano-testnet"
+  else
+    echo "ERROR: isNg must be either true to use the pre-release (aka next generation or \"ng\") version of node and cli,"
+    echo "       or false to use the release version of node and cli."
+    exit 1
+  fi
+
+  export CARDANO_CLI
+  export CARDANO_NODE
+  eval "$CARDANO_TESTNET" {{ARGS}}
+
 # Deploy a cloudFormation stack
 cf STACKNAME:
   #!/usr/bin/env nu
